from franklinwh.client import MODE_EMERGENCY_BACKUP, MODE_SELF_CONSUMPTION, MODE_TIME_OF_USE

print(f"MODE_EMERGENCY_BACKUP = '{MODE_EMERGENCY_BACKUP}'")
print(f"MODE_SELF_CONSUMPTION = '{MODE_SELF_CONSUMPTION}'")
print(f"MODE_TIME_OF_USE = '{MODE_TIME_OF_USE}'")
